draft PR for generic read config
EESSI/eessi-bot-software-layer pull request #128
Opened 2022-12-16 02:52 UTC by Hafsa-Naeem

2022-12-19 08:22 UTC, boegel requested changes

2022-12-19 08:22 UTC, boegel commented on tasks/deploy.py
> +    cfg = read_config(DEPLOYCFG, DEPLOY_PERMISSION)
`read_config` should be a function that is imported from `tools.config`, which reads a given configuration file at a specified path, and returns the configuration (as a dictionary). The idea is that this replaces the usage of the `read_file` (which is called in the `main` function in `eessi_bot_job_manager.py` and `eessi_bot_job_manager.py`) and `get_section` functions (both can be removed), as follows:

```python
cfg = read_config('app.cfg')
...
if labeler not in cfg[DEPLOYCFG][DEPLOY_PERMISSION]:
...
upload_policy = cfg[DEPLOYCFG][DEPLOY_PERMISSION]
```

That way, we can stop using the global variable `_config` in `tools/config.py`, which is initialized

2022-12-19 08:25 UTC, boegel commented on tasks/deploy.py
> +    cfg = read_config(DEPLOYCFG, DEPLOY_PERMISSION)
or:

```python
cfg = read_config('app.cfg')
deploy_cfg = cfg[DEPLOYCFG]
...
if labeler not in deploy_cfg[DEPLOY_PERMISSION]:

2022-12-19 08:26 UTC, trz42 requested changes

2022-12-19 08:26 UTC, trz42 commented on tasks/deploy.py
> +def read_config(cfg, option=None):
Please add docstring for `read_config`

2022-12-21 09:05 UTC, boegel commented
replaced by #130

2022-12-21 09:05 UTC, closed without merging