[v0.1] code polishing: tools/filter.py
EESSI/eessi-bot-software-layer pull request #205
Opened 2023-08-08 13:12 UTC by trz42

Code polishing pass on `tools/filter.py` for release v0.1:

- imports: same categorisation of imports
- docstrings: slightly rephrased some + added a missing information
- comments: improved some comments

2023-08-08 18:03 UTC, boegel requested changes

2023-08-08 18:03 UTC, boegel commented on tools/filter.py
> +            # if full_component == 'architecture' replace '-' with '/' in
`replace '-' with '/' in pattern when using 'architecture' filter component`

2023-08-08 18:03 UTC, boegel commented on tools/filter.py
> +            string containing whitespace separated filters
`string containing filters separated by whitespace`

2023-08-08 20:05 UTC, trz42 commented on tools/filter.py
> +               to 'component:pattern' format or pattern is empty
Args description was wrong. Nice catch!

2023-08-08 20:10 UTC, trz42 commented on tools/filter.py
>              if cis.startswith(component):
I will open an issue. Ideally the procedure would check if the prefix is unique, refuses to process it if not, and provides some guidance. For example, _Component 're' is ambiguous (could be 'repository' or 'request'). Resent the command with a longer unambiguous prefix._

2023-08-16 11:39 UTC, boegel commented on tools/filter.py
>              if cis.startswith(component):
issue opened at #210

2023-08-16 11:41 UTC, boegel approved these changes

2023-08-16 11:41 UTC, merged