remove references to 'pilot', switch to software.eessi.io
EESSI/eessi-bot-software-layer pull request #229
Opened 2023-11-15 18:15 UTC by trz42

Mostly changes in examples, README.md and tests. Only a single code file (`tasks/build.py`) had to be changed.

Implementation (use with bot instances) should be coordinated with software-layer PR https://github.com/EESSI/software-layer/pull/383

2023-11-23 12:39 UTC, trz42 commented on tasks/build.py
> +            if repo_id != "EESSI" and repo_id not in repocfg:
use `startswith` to ensure that `EESSI-pilot` still works

_OR_

use explicit `or`

2023-11-23 12:39 UTC, boegel requested changes

2023-11-23 12:39 UTC, boegel commented on tasks/build.py
> +            if repo_id != "EESSI" and repo_id not in repocfg:
```suggestion
            if (repo_id != "EESSI" and repo_id != "EESSI-pilot") and repo_id not in repocfg:

2023-11-26 11:32 UTC, boegel requested changes

2023-11-26 11:32 UTC, boegel commented on README.md
> +config_map = {"eessi.io/cvmfs-config.eessi.io.pub":"/etc/cvmfs/keys/eessi.io/cvmfs-config.eessi.io.pub", "eessi.io/ci.eessi.io.pub":"/etc/cvmfs/keys/eessi.io/ci.eessi.io.pub", "eessi.io/software.eess
There's no `ci.eessi.io` or `cvmfs-config.eessi.io` repo, so this should be cleaned up.

In addition, `software.eessi.io.pub` should be renamed to `eessi.io.pub`:

```suggestion
config_map = {"eessi.io/eessi.io.pub":"/etc/cvmfs/keys/eessi.io/eessi.io.pub", "default.local":"/etc/cvmfs/default.local", "eessi.io.conf":"/etc/cvmfs/domain.d/eessi.io.conf"}

2023-11-26 12:30 UTC, boegel approved these changes

2023-11-26 12:30 UTC, merged