added methods for refactoring
EESSI/eessi-bot-software-layer pull request #52
Opened 2022-10-24 09:44 UTC by Hafsa-Naeem

fixes #36, fixes #35

2022-10-24 10:34 UTC, Hafsa-Naeem commented
fixes #36

2022-10-24 12:20 UTC, boegel requested changes

2022-10-24 12:20 UTC, boegel commented on tasks/build.py
>      for arch_target,slurm_opt in arch_target_map.items():
suggestion: create functions for what's done *in* the loop body, something like:

```python
for arch_target,slurm_opt in arch_target_map.items():
        arch_job_dir = os.path.join(run_dir, arch_target.replace('/', '_'))
        mkdir(arch_job_dir)
        log("arch_job_dir '%s'" % arch_job_dir)

        set_up_pr_in(repo_name, pr_number, arch_job_dir)
        apply_customisations(arch_job_dir, cvmfs_customizations)

2022-10-24 12:20 UTC, boegel commented on tasks/build.py
> +    jobs_base_dir, local_tmp, build_job_script, submit_command, slurm_params, cvmfs_customizations, http_proxy, https_proxy, load_modules = get_build_env()
maybe this approach is better:

```python
build_env_cfg = get_build_env_configuration()
```
and use constants:
```python
SUBMIT_COMMAND = 'submit_command'
```
in `get_build_env_configuration`:
```python
    buildenv = config.get_section('buildenv')
    ...
    submit_command = buildenv.get(SUBMIT_COMMAND)
```

where you need the submit command, use:
```python
build_env_cfg[SUBMIT_COMMAND]
```
and pass down `build_env_cfg`:
```python
    repo_name, jobs = download_pull_request(pr, arch_target_map, run_dir, build_env_cfg)
    for job in jobs:
        submit_job(job, build_env_cfg)

2022-10-24 12:25 UTC, boegel requested changes

2022-10-24 12:25 UTC, boegel commented on tasks/build.py
> +def create_directory(pr, jobs_base_dir, event_info):
Please also add a docstring, maybe also add [type hints](https://docs.python.org/3/library/typing.html) in the function signature:

```python
def create_directory(pr: int, jobs_base_dir: str, event_info: dict) -> (str, str, str)
    """
    Create directory for PR

    :param pr: PR number
    :param jobs_base_dir: location ...
    :returns: tuple of 3 elements: string with datestamp (<year>.<month>)
    """

2022-10-26 08:26 UTC, boegel requested changes

2022-10-26 08:26 UTC, boegel commented on tasks/build.py
>          #  - PR_NUMBER is pr.number
move this comment into `setup_pr_in_arch_job_dir`?

2022-10-26 08:26 UTC, boegel commented on tasks/build.py
> +LOAD_MODULES = "load_modules"
please sort these alphabetically:

```python
BUILD_JOB_SCRIPT = ...
CVMFS_CUSTOMIZATIONS = ...
...
```

2022-10-26 08:26 UTC, boegel commented on tasks/build.py
>  def mkdir(path):
also docstring here?

2022-10-26 08:26 UTC, boegel commented on tasks/build.py
> +def apply_cvmfs_customizations(cvmfs_customizations,arch_job_dir):
please add a docstring + two empty lines above function definition

2022-10-26 08:26 UTC, boegel commented on tasks/build.py
> +def build_easystack_from_pr(pr, event_info):
also add a docstring here

2022-10-26 08:26 UTC, boegel commented on tasks/build.py
> +    slurm_params = buildenv.get(SLURM_PARAMS)
This should become:

```python
slurm_params = buildenv.get(SLURM_PARAMS)
# always submit jobs with hold set, so job manager can release them
slurm_params += ' --hold'
```

which fixes #35

2022-10-27 07:17 UTC, boegel approved these changes
lgtm, tested with https://github.com/boegel/software-layer/pull/11 :+1:

2022-10-27 07:17 UTC, merged