non bot jobs
EESSI/eessi-bot-software-layer pull request #63
Opened 2022-11-14 09:09 UTC by Hafsa-Naeem

2022-11-14 09:32 UTC, boegel requested changes

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +            return None
This function should also actually *read* the metadata file, if it exists (see `metadata.read(job_metadata_path)` below)

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +                    metadata_pr = metadata["PR"]
This can also go into the `read_job_pr_metadata` function

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +            if not "comment_id" in finished_job:
```python
if "comment_id" not in finished_job:

2022-11-14 09:32 UTC, boegel commented on tests/test_eessi_bot_job_manager.py
> +from eessi_bot_job_manager import EESSIBotSoftwareLayerJobManager()
should be:

```python
from eessi_bot_job_manager import EESSIBotSoftwareLayerJobManager

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +                repo_name = metadata_pr["repo"] or ""
this is safer:

```python
                repo_name = metadata_pr.get("repo", "")

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +                pr_number = metadata_pr["pr_number"] or None
also here:

```python
pr_number = metadata_pr.get("pr_number", None)

2022-11-14 09:32 UTC, boegel commented on tests/test_eessi_bot_job_manager.py
> +        fp.write("...")
contents of the file should be:

```
[PR]
repo=test
pr_number=12345

2022-11-14 09:32 UTC, boegel commented on tests/test_eessi_bot_job_manager.py
> +    assert metadata is not None
```python
metadata_pr = read_job.read_job_pr_metadata(path)
expected = {
    "repo": "test",
    "pr_number": "12345",
}
assert metadata_pr == expected

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +        job_manager.scontrol_command = job_mgr.get("scontrol_command") or false
use `False`

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +                # comment_update += '\nAn admin may investigate what went wrong. (TODO implement procedure to ask for details by adding a command to this comment.)'
```python
# comment_update += '\nAn admin may investigate what went wrong. (TODO implement procedure to ask '
# comment_update += 'for details by adding a command to this comment.)'

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +                            tarball_pattern.replace("*", "\*"),
```python
tarball_pattern.replace(r"*", r"\*"),

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +                error(f"Unable to read job metadata file {job_metadata_path}!")
missing import?

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +        match = re.search(".* WorkDir=(\S+) .*", str(scontrol.stdout, "UTF-8"))
use `r"..." (raw string)

```python
         match = re.search(r".* WorkDir=(\S+) .*", str(scontrol.stdout, "UTF-8"))

2022-11-14 09:32 UTC, boegel commented on .nfsff795e7615d590070000011a
> +python3 -m eessi_bot_event_handler "$@"
This file should be removed

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +            return None
So this function should do 3 things:

* check if the file exists, return `None` if not
* if the file exists, read it, extract the `PR` section, and return that as a value

2022-11-14 09:32 UTC, boegel commented on eessi_bot_job_manager.py
> +        if isfile is False:
cleaner:

```python
        log("The test for metafile returns: %s" % isfile)
        if os.path.isfile(job_metadata_path):
            # read file + extract PR section + return
        else:
            log("...")
            return None

2022-11-16 08:21 UTC, trz42 commented on eessi_bot_job_manager.py
> +from pyghee.utils import create_file, log, error
Should become
```python
from pyghee.utils import log, error

2022-11-16 09:06 UTC, boegel requested changes

2022-11-16 09:34 UTC, merged